refresh materialized view concurrently k3l_profiles;
refresh materialized view k3l_posts;
refresh materialized view k3l_follows;
refresh materialized view k3l_mirrors;
refresh materialized view k3l_comments;
refresh materialized view k3l_collect_nft;
refresh materialized view k3l_follow_counts;
refresh materialized view k3l_upvotes;
refresh materialized view k3l_interactions;
refresh materialized view concurrently k3l_feed;
refresh materialized view concurrently k3l_following_feed;
refresh materialized view concurrently k3l_rank;